name: deploy hugo pages

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: build on target
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./stage.vvvv.org/build.sh
          host: 'vvvv.org'
          username: vvvv
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
